name: Deploy Web Production

on:
  push:
    branches:
      - web-prod-deploy
    paths:
      - 'web.skillflow.com/**'

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e

            echo "Go to project..."
            cd /opt/apps/Skill-Flow

            echo "Checkout deployment branch..."
            git fetch origin
            git checkout web-prod-deploy
            git reset --hard origin/web-prod-deploy

            echo "Go to web project..."
            cd web.skillflow.com

            echo "Build image..."
            docker compose build --no-cache

            echo "Restart container..."
            docker compose up -d

            echo "Cleanup..."
            docker image prune -f

            docker compose ps