name: Deploy Web Staging

on:
  push:
    branches:
      - web-stage-deploy
    paths:
      - "web.skillflow.com/**"
      - ".github/workflows/deploy-web-staging.yml"

  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Web Staging
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Copy Web Project to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "web.skillflow.com/*"
          target: "/opt/apps/staging/web"
          overwrite: true

      - name: Deploy Staging Web
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e

            APP_DIR="/opt/apps/staging/web/web.skillflow.com"
            
            COMPOSE_FILE="docker-compose.stage.yml"

            echo "========== APPLICATION DIRECTORY =========="
            cd "$APP_DIR"
            pwd

            echo "========== PROJECT FILES =========="
            ls -la

            echo "========== STAGING COMPOSE FILE =========="
            test -f "$COMPOSE_FILE"
            cat "$COMPOSE_FILE"

            echo "========== VALIDATE COMPOSE =========="
            docker compose -f "$COMPOSE_FILE" config

            echo "========== BUILD STAGING IMAGE =========="
            docker compose -f "$COMPOSE_FILE" build --no-cache

            echo "========== START STAGING CONTAINER =========="
            docker compose -f "$COMPOSE_FILE" up -d --remove-orphans

            echo "========== CONTAINER STATUS =========="
            docker compose -f "$COMPOSE_FILE" ps

            echo "========== REMOVE UNUSED IMAGES =========="
            docker image prune -f